### ISSUE TITLE
Add proper data-cy selectors for file picker

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud-libraries/nextcloud-dialogs#1001] opened 2023-09-14 15:56 UTC
It would be great to have unique selectors for elements, especially file list entries to pick them during testing

https://docs.cypress.io/guides/references/best-practices

For files we currently only can use the title attribute which doesn't contain the file extension

**Comment by susnux** [comment] 2023-09-17 12:54
Duplicate of https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/924 (partly implemented https://github.com/nextcloud-libraries/nextcloud-dialogs#test-selectors )

**Closed** 2023-09-17 13:00 UTC
