### ISSUE TITLE
FilePicker: Display issues when used via Smart Picker

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud-libraries/nextcloud-dialogs#887] opened 2023-08-15 08:47 UTC
see c.nc.c and tech-preview

Just now with admin user "jos" on tech-preview.nextcloud.com
![Peek 2023-08-15 10-04](https://github.com/nextcloud/server/assets/551757/4ae654c4-f87b-458a-a496-f4904dba70fd)

**Comment by susnux** [comment] 2023-08-15 18:05
Caused by the reference element here:
https://github.com/nextcloud/server/blob/3c13efdaf20e233ead133690e3072085f7cffc84/apps/files/src/views/FileReferencePickerElement.vue

**Comment by jospoortvliet** [comment] 2023-08-16 11:57
Thanks for fixing, Ferdinand.

**Comment by susnux** [comment] 2023-08-16 15:01
fixed with beta3

**Closed by susnux** 2023-08-16 15:01 UTC
Labels: bug, 🍁 2023-Autumn
